// import localFont from "next/font/local";
import "./globals.css";

// const circularweb = localFont({
//   src: [{ path: "./fonts/circularweb-book.woff2", style: "normal" }],
// });

// const x = [
//   { path: "./fonts/general.woff2" },
//   { path: "./fonts/robert-medium.woff2", style: "normal" },
//   { path: "./fonts/robert-regular.woff2", style: "normal" },
//   { path: "./fonts/zentry-regular.woff2", style: "normal" },
// ];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
